### ISSUE TITLE
Successfully setup but error on an npm command

### ISSUE THREAD

**Issue by Venipa** [MohamedLamineAllal/laravel-mix-glob#2]
```events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: spawn npm ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
error Command failed with exit code 1.```

**Comment by Venipa** [comment]
made a fix for this error https://github.com/MohamedLamineAllal/laravel-mix-glob/pull/3

**Comment by MohamedLamineAllal** [comment]
@Venipa thank you for the contribution
