### ISSUE TITLE
Error when executing `npm run dev`

### ISSUE THREAD

**Issue by dweinerATL** [MohamedLamineAllal/laravel-mix-glob#5]
When I execute `npm run dev`, I get the following error

`TypeError: Cannot read property 'js' of undefined`

My `webpack.mix.js` file is as follows:

```
const mix = require('laravel-mix');
const MixGlob = require('laravel-mix-glob');
const mixGlob = MixGlob({mix});

mixGlob.js('resources/js/*.js', 'public/js/app.js', null, {
    base: 'resources/js/'
})
    .sass('resources/sass/*.scss', 'public/css/app.css', null, {
        base: 'resources/sass/'
    });
```

If I change the order so that the sass resources are compiled first, the error message is
`TypeError: Cannot read property 'sass' of undefined`

npm error log:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node@10/10.16.3/bin/node',
1 verbose cli   '/usr/local/opt/node@10/bin/npm',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@6.9.0
3 info using node@v10.16.3
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle @~predev: @
6 info lifecycle @~dev: @
7 verbose lifecycle @~dev: unsafe-perm in lifecycle true
8 verbose lifecycle @~dev: PATH: /usr/local/Cellar/node@10/10.16.3/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/davidweiner/Sites/core/node_modules/.bin:/usr/local/opt/node@10/bin:/usr/local/opt/icu4c/sbin:/usr/local/opt/icu4c/bin:/Users/davidweiner/.composer/vendor/bin/:/usr/local/opt/php/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/davidweiner/Sites/core/node_modules/.bin
9 verbose lifecycle @~dev: CWD: /Users/davidweiner/Sites/core
10 silly lifecycle @~dev: Args: [ '-c', 'npm run development' ]
11 silly lifecycle @~dev: Returned: code: 1  signal: null
12 info lifecycle @~dev: Failed to exec dev script
13 verbose stack Error: @ dev: `npm run development`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/Cellar/node@10/10.16.3/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/Cellar/node@10/10.16.3/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid @
15 verbose cwd /Users/davidweiner/Sites/core
16 verbose Darwin 18.7.0
17 verbose argv "/usr/local/Cellar/node@10/10.16.3/bin/node" "/usr/local/opt/node@10/bin/npm" "run" "dev"
18 verbose node v10.16.3
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error @ dev: `npm run development`
22 error Exit status 1
23 error Failed at the @ dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

If I remove
```
mixGlob.js('resources/js/*.js', 'public/js/app.js', null, {
    base: 'resources/js/'
})
    .sass('resources/sass/*.scss', 'public/css/app.css', null, {
        base: 'resources/sass/'
    });
```
and replace it with
```
mix.js('resources/js/app.js', 'public/js')
    .sass('resources/sass/app.scss', 'public/css');
```

it will run just fine, and I get the following lines of output:
```
$ npm run dev

> @ dev /Users/davidweiner/Sites/core
> npm run development


> @ development /Users/davidweiner/Sites/core
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

  MixGlob:debug !!!!! ----- No debug env var ----- !!!! +0ms
  MixGlob:debug env vars: +2ms
  MixGlob:debug [ 'npm_config_save_dev',
  MixGlob:debug   'npm_config_legacy_bundling',
  MixGlob:debug   'npm_config_dry_run',
  MixGlob:debug   'npm_package_devDependencies_resolve_url_loader',
  MixGlob:debug   'npm_config_only',
  MixGlob:debug   'npm_config_browser',
  MixGlob:debug   'npm_config_commit_hooks',
  MixGlob:debug   'npm_config_viewer',
  MixGlob:debug   'npm_package_gitHead',
  MixGlob:debug   'npm_package_scripts_watch_poll',
  MixGlob:debug   'LDFLAGS',
  MixGlob:debug   'npm_config_also',
  MixGlob:debug   'npm_config_sign_git_commit',
  MixGlob:debug   'npm_config_rollback',
  MixGlob:debug   'npm_config_usage',
  MixGlob:debug   'npm_config_audit',
  MixGlob:debug   'npm_package_devDependencies_popper_js',
  MixGlob:debug   'npm_package_devDependencies_laravel_mix',
  MixGlob:debug   'NODE',
  MixGlob:debug   'npm_package_dependencies_flag_icon_css',
  MixGlob:debug   'npm_package_devDependencies__fortawesome_fontawesome_free',
  MixGlob:debug   'npm_package_scripts_prod',
  MixGlob:debug   'INIT_CWD',
  MixGlob:debug   'npm_config_globalignorefile',
  MixGlob:debug   'TERM',
  MixGlob:debug   'SHELL',
  MixGlob:debug   'npm_config_init_author_url',
  MixGlob:debug   'npm_config_maxsockets',
  MixGlob:debug   'npm_config_shell',
  MixGlob:debug   'npm_package_devDependencies_vue_template_compiler',
  MixGlob:debug   'npm_config_parseable',
  MixGlob:debug   'npm_config_metrics_registry',
  MixGlob:debug   'npm_config_shrinkwrap',
  MixGlob:debug   'CPPFLAGS',
  MixGlob:debug   'TMPDIR',
  MixGlob:debug   'npm_config_timing',
  MixGlob:debug   'npm_config_init_license',
  MixGlob:debug   'npm_package_scripts_development',
  MixGlob:debug   'Apple_PubSub_Socket_Render',
  MixGlob:debug   'npm_config_if_present',
  MixGlob:debug   'npm_package_devDependencies_jquery',
  MixGlob:debug   'npm_package_scripts_dev',
  MixGlob:debug   'npm_config_sign_git_tag',
  MixGlob:debug   'npm_config_init_author_email',
  MixGlob:debug   'npm_config_cache_max',
  MixGlob:debug   'npm_package_devDependencies_sass_loader',
  MixGlob:debug   'npm_config_preid',
  MixGlob:debug   'npm_config_long',
  MixGlob:debug   'npm_config_local_address',
  MixGlob:debug   'npm_config_cert',
  MixGlob:debug   'npm_config_git_tag_version',
  MixGlob:debug   'npm_config_noproxy',
  MixGlob:debug   'npm_config_fetch_retries',
  MixGlob:debug   'npm_config_registry',
  MixGlob:debug   'npm_package_private',
  MixGlob:debug   'npm_config_versions',
  MixGlob:debug   'npm_config_key',
  MixGlob:debug   'npm_config_message',
  MixGlob:debug   'USER',
  MixGlob:debug   'npm_config_globalconfig',
  MixGlob:debug   'npm_config_prefer_online',
  MixGlob:debug   'npm_config_always_auth',
  MixGlob:debug   'npm_config_logs_max',
  MixGlob:debug   'SSH_AUTH_SOCK',
  MixGlob:debug   '__CF_USER_TEXT_ENCODING',
  MixGlob:debug   'npm_execpath',
  MixGlob:debug   'npm_config_global_style',
  MixGlob:debug   'npm_config_cache_lock_retries',
  MixGlob:debug   'npm_config_cafile',
  MixGlob:debug   'npm_config_update_notifier',
  MixGlob:debug   'npm_config_audit_level',
  MixGlob:debug   'npm_config_heading',
  MixGlob:debug   'npm_config_read_only',
  MixGlob:debug   'npm_config_offline',
  MixGlob:debug   'npm_config_fetch_retry_mintimeout',
  MixGlob:debug   'npm_config_searchlimit',
  MixGlob:debug   'npm_config_json',
  MixGlob:debug   'npm_config_access',
  MixGlob:debug   'npm_config_argv',
  MixGlob:debug   'npm_package_dependencies_selectize',
  MixGlob:debug   'PATH',
  MixGlob:debug   'npm_config_allow_same_version',
  MixGlob:debug   'TERMINAL_EMULATOR',
  MixGlob:debug   'npm_config_https_proxy',
  MixGlob:debug   'npm_config_engine_strict',
  MixGlob:debug   'npm_config_description',
  MixGlob:debug   'npm_package_scripts_hot',
  MixGlob:debug   '_',
  MixGlob:debug   'npm_config_init_module',
  MixGlob:debug   'npm_config_userconfig',
  MixGlob:debug   'npm_config_cidr',
  MixGlob:debug   'PWD',
  MixGlob:debug   'npm_config_user',
  MixGlob:debug   'npm_config_node_version',
  MixGlob:debug   'JAVA_HOME',
  MixGlob:debug   'npm_lifecycle_event',
  MixGlob:debug   'npm_config_ignore_prepublish',
  MixGlob:debug   'npm_config_auth_type',
  MixGlob:debug   'npm_config_editor',
  MixGlob:debug   'npm_config_save',
  MixGlob:debug   ... 119 more items ] +1ms
  MixGlob Mix glob +0ms
98% after emitting SizeLimitsPlugin

 DONE  Compiled successfully in 9904ms
```

**Comment by MohamedLamineAllal** [comment]
Hi there my friend.

I'm late again. And i'm super sorry. The whole thing is super stupid. And my bad.
My documentation had a mistake. It's updated now.

We initialize with construction and using `new`. I had some portion of the documentation that were showing that. And other that were wrong. Including the first example. My bad it's  fixed now.

```javascript
const mix = require('laravel-mix');
const MixGlob = require('laravel-mix-glob');
const mixGlob = new MixGlob({mix}); // <----------- new MixGlob()

mixGlob.js('resources/js/*.compile.js', 'public/js/app.js', null, {
    base: 'resources/js/'
})
.sass('resources/sass/*.compile.scss', 'public/css/app.css', null, {
    base: 'resources/sass/'
});
```
Your old code
![Screenshot from 2019-10-03 16-09-19](https://user-images.githubusercontent.com/20062543/66139573-97075100-e5f8-11e9-92ef-c4ce8f6db454.png)

Doing it right
![Screenshot from 2019-10-03 16-07-00](https://user-images.githubusercontent.com/20062543/66139576-97075100-e5f8-11e9-94c7-f10fe834d78d.png)

Sorry for that. Give it a try. Also it's very appreciated if you help maintain the project too. (Just saying hhh)

**Comment by donquixote** [comment]
Hi!
I have the same problem, and it is not explained by the response.

It can be reduced to the following webpack.min.js:

```js
const MixGlob = require('laravel-mix-glob');
```
-> "!!!!! ----- No debug env var ----- !!!!"

```js
process.env.DEBUG = false;
const MixGlob = require('laravel-mix-glob');
```
-> no warnings

The code in `noDebugEnvVar()` suggests that we need at least one of the following keys in `process.env`:
The variables are explained on https://github.com/visionmedia/debug, and the same variables are also used in DEBUG_ENV_VARS in laravelMixGlob.min.js.

| Name      | Purpose                                         |
|-----------|-------------------------------------------------|
| `DEBUG`   | Enables/disables specific debugging namespaces. |
| `DEBUG_HIDE_DATE` | Hide date from debug output (non-TTY).  |
| `DEBUG_COLORS`| Whether or not to use colors in the debug output. |
| `DEBUG_DEPTH` | Object inspection depth.                    |
| `DEBUG_SHOW_HIDDEN` | Shows hidden properties on inspected objects. |

This leads me to the following questions:
- Where do I configure these variables for `process.env`?
- What are reasonable default values?
- Why does this package make noise if none of the variables are defined?
- Why is it enough to set _one_ of those variables?
