### ISSUE TITLE
Error: read ENOTCONN

### ISSUE THREAD

**Issue by angieschmitt** [MohamedLamineAllal/laravel-mix-glob#59]
Having an issue running 'mix watch' while using mixglob... Getting the following error:

Error: read ENOTCONN
    at tryReadStart (net.js:575:20)
    at WriteStream.Socket._read (net.js:586:5)
    at WriteStream.Readable.read (internal/streams/readable.js:462:10)
    at WriteStream.Socket.read (net.js:627:39)
    at resume_ (internal/streams/readable.js:958:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
Emitted 'error' event on WriteStream instance at:
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
      errno: -4053,
      code: 'ENOTCONN',
      syscall: 'read'
    }

It almost seems like it's trying to call watch twice, and the files are still locked from the previous run.

Any ideas?

**Comment by gregrobsonoxb** [comment]
I'm getting a similar issue. My home PC is much faster than my work computer. Is it *too* fast? 😆  

```
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: read ENOTCONN
    at tryReadStart (net.js:574:20)
    at WriteStream.Socket._read (net.js:585:5)
    at WriteStream.Readable.read (internal/streams/readable.js:481:10)
    at WriteStream.Socket.read (net.js:625:39)
    at resume_ (internal/streams/readable.js:968:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on WriteStream instance at:
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -4053,
  code: 'ENOTCONN',
  syscall: 'read'
}
```

**Comment by MohamedLamineAllal** [comment]
@angieschmitt  @gregrobsonoxb please check the v2
